# Generated by Django 2.2.1 on 2019-07-05 05:08

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200, unique=True)),
                ('event_pic', models.ImageField(null=True, upload_to='events/%Y/%m/%d/')),
                ('event_detail', ckeditor.fields.RichTextField(null=True)),
                ('event_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('event_contact_person', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('event_contact', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
