# Generated by Django 2.2.1 on 2019-07-03 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_contact',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_contact_person',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
