# Generated by Django 2.2.1 on 2019-07-04 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20190703_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_pic',
            field=models.ImageField(null=True, upload_to='events/%Y/%m/%d/'),
        ),
    ]
