# Generated by Django 2.2.1 on 2019-07-05 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_contact_us'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_contact_person',
        ),
    ]
