# Generated by Django 2.2.1 on 2019-07-05 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_event_event_contact_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='contact_email',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
