# Generated by Django 2.2.1 on 2019-07-04 09:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_event_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_detail',
            field=ckeditor.fields.RichTextField(max_length=300, null=True),
        ),
    ]
