# Generated by Django 2.2.1 on 2019-07-04 09:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_event_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_detail',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
