# Generated by Django 2.2.1 on 2019-07-05 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_contact_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='contact_email',
            new_name='contact_location',
        ),
    ]
