# Generated by Django 2.2.1 on 2019-07-05 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20190705_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_contact',
        ),
    ]
