# Generated by Django 2.2.1 on 2019-07-05 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_1',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_2',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
