# Generated by Django 2.2.1 on 2019-05-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='picture1',
            field=models.ImageField(blank=True, null=True, upload_to='picture/'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='picture2',
            field=models.ImageField(blank=True, null=True, upload_to='picture/'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='picture3',
            field=models.ImageField(blank=True, null=True, upload_to='picture/'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='picture4',
            field=models.ImageField(blank=True, null=True, upload_to='picture/'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='picture5',
            field=models.ImageField(blank=True, null=True, upload_to='picture/'),
        ),
    ]
