# Generated by Django 2.2.1 on 2019-05-10 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20190510_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='picture1',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='picture2',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='picture3',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='picture4',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='picture5',
        ),
    ]
