# Generated by Django 2.2.1 on 2019-05-06 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20190506_1754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='timestamp',
            new_name='reload',
        ),
        migrations.RenameField(
            model_name='header',
            old_name='timestamp',
            new_name='reload',
        ),
    ]
