# Generated by Django 2.2.1 on 2019-05-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_auto_20190510_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='statements',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
