# Generated by Django 2.2.1 on 2019-05-07 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
