# Generated by Django 2.2.1 on 2019-05-09 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_auto_20190507_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_header',
            field=models.ImageField(blank=True, null=True, upload_to='team_header/'),
        ),
    ]
