# Generated by Django 2.2.1 on 2019-05-09 19:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_team_team_header'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teamhead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('team_header', models.ImageField(blank=True, null=True, upload_to='home_header/')),
                ('logo_short_name', models.CharField(blank=True, max_length=20, null=True)),
                ('motivational_statement', models.CharField(blank=True, max_length=20, null=True)),
                ('reload', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
    ]
