# Generated by Django 2.2.1 on 2019-05-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_teamhead'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
