# Generated by Django 2.2.1 on 2019-05-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190509_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topbar',
            name='statement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
