# Generated by Django 2.1.7 on 2019-05-13 02:35

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190511_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footer',
            old_name='phone1',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='description',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='phone2',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='youtube',
        ),
        migrations.AlterField(
            model_name='head',
            name='motivational_statement',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='topbar',
            name='statement',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
