# Generated by Django 2.1.7 on 2019-06-18 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20190614_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='head',
            name='home_header_4',
        ),
        migrations.RemoveField(
            model_name='head',
            name='home_header_5',
        ),
    ]
